export interface Student {
  id: string;
  className: "8A" | "8C" | "8E" | "9C" | "9E" | "9F";
  studentNumber: number;
  studentName: string;
}

export const AVAILABLE_CLASSES: Array<Student["className"]> = [
  "8A",
  "8C",
  "8E",
  "9C",
  "9E",
  "9F",
];

export const MASTER_ROSTER: Student[] = [
  // ==========================================
  // KELAS 8A (32 Siswa)
  // ==========================================
  { id: "8a-1", className: "8A", studentNumber: 1, studentName: "ACHMAD ZAAHIR SYAHBANI" },
  { id: "8a-2", className: "8A", studentNumber: 2, studentName: "AFIF ABID SURUR" },
  { id: "8a-3", className: "8A", studentNumber: 3, studentName: "AL NESTA PUTRA SETIAWAN" },
  { id: "8a-4", className: "8A", studentNumber: 4, studentName: "ALESHA DEAVIKA TAUFAN" },
  { id: "8a-5", className: "8A", studentNumber: 5, studentName: "AMARTYA GAYATRI TEJARESWARI" },
  { id: "8a-6", className: "8A", studentNumber: 6, studentName: "ASYLA SYA'BAN QURRATU'AININ" },
  { id: "8a-7", className: "8A", studentNumber: 7, studentName: "AURUMMA NAJWA WICHITA" },
  { id: "8a-8", className: "8A", studentNumber: 8, studentName: "CHRISTIAN RIZKY DWIPUTRA" },
  { id: "8a-9", className: "8A", studentNumber: 9, studentName: "ERRENS LADY NATHALIA" },
  { id: "8a-10", className: "8A", studentNumber: 10, studentName: "GENDHIS FANNYNA LIONA POETRI" },
  { id: "8a-11", className: "8A", studentNumber: 11, studentName: "GLORY DINA CHRISTIANI" },
  { id: "8a-12", className: "8A", studentNumber: 12, studentName: "HAIDAR AHMAD NABIL" },
  { id: "8a-13", className: "8A", studentNumber: 13, studentName: "INTAN KARUNIA TOHATU" },
  { id: "8a-14", className: "8A", studentNumber: 14, studentName: "JASMIEN ISNAINI SELAWATI" },
  { id: "8a-15", className: "8A", studentNumber: 15, studentName: "KADEK MAHATMA SATYA PRADIPTA" },
  { id: "8a-16", className: "8A", studentNumber: 16, studentName: "KANZA FITRI RAMADHANI" },
  { id: "8a-17", className: "8A", studentNumber: 17, studentName: "KIRANIA ADREENA CARISSA" },
  { id: "8a-18", className: "8A", studentNumber: 18, studentName: "LYRA SALSABILLA PUTRI WARDHANA" },
  { id: "8a-19", className: "8A", studentNumber: 19, studentName: "M ZHAFRAN ABQARY WAFI" },
  { id: "8a-20", className: "8A", studentNumber: 20, studentName: "MOHAMMAD KENZA RADITYA" },
  { id: "8a-21", className: "8A", studentNumber: 21, studentName: "MUH AFANDY RAMADHAN" },
  { id: "8a-22", className: "8A", studentNumber: 22, studentName: "MUHAMMAD JINDAN AKBAR" },
  { id: "8a-23", className: "8A", studentNumber: 23, studentName: "MUHAMMAD QAISER AFDHALI" },
  { id: "8a-24", className: "8A", studentNumber: 24, studentName: "NAFISYA AYUNDI RADISTHI" },
  { id: "8a-25", className: "8A", studentNumber: 25, studentName: "NAUFAL AHMAD DZAKII" },
  { id: "8a-26", className: "8A", studentNumber: 26, studentName: "NEYSA ATHALLAH FAJRINA" },
  { id: "8a-27", className: "8A", studentNumber: 27, studentName: "NURIN NAJWA" },
  { id: "8a-28", className: "8A", studentNumber: 28, studentName: "PETRUS NANDO AMADEO" },
  { id: "8a-29", className: "8A", studentNumber: 29, studentName: "RAFA RADITHYA YUNANSYAH" },
  { id: "8a-30", className: "8A", studentNumber: 30, studentName: "RIDWAN DWI RAMADHAN" },
  { id: "8a-31", className: "8A", studentNumber: 31, studentName: "WELLBYANO KARYA PUTRA" },
  { id: "8a-32", className: "8A", studentNumber: 32, studentName: "ZAHRA AULIA PUTRI" },

  // ==========================================
  // KELAS 8C (32 Siswa)
  // ==========================================
  { id: "8c-1", className: "8C", studentNumber: 1, studentName: "ABDURRAHMAN REZA PASHA" },
  { id: "8c-2", className: "8C", studentNumber: 2, studentName: "AMALAH SAFANA FURNIALIKAH" },
  { id: "8c-3", className: "8C", studentNumber: 3, studentName: "ANDINI TATA ARTI" },
  { id: "8c-4", className: "8C", studentNumber: 4, studentName: "ATHAR FIRASH WARDHANA" },
  { id: "8c-5", className: "8C", studentNumber: 5, studentName: "ATHAYA NAZNEEN SAHRIZAL" },
  { id: "8c-6", className: "8C", studentNumber: 6, studentName: "AYCHILLA ARUNY FALERINE AGATHA" },
  { id: "8c-7", className: "8C", studentNumber: 7, studentName: "AZZAHRA NOVELITA FADILLAH" },
  { id: "8c-8", className: "8C", studentNumber: 8, studentName: "DENIZ FARSHAD" },
  { id: "8c-9", className: "8C", studentNumber: 9, studentName: "DZAHARA PUTRI AMELLIA" },
  { id: "8c-10", className: "8C", studentNumber: 10, studentName: "ERICK KURNIAWAN" },
  { id: "8c-11", className: "8C", studentNumber: 11, studentName: "HASAN AMMAAR SENO" },
  { id: "8c-12", className: "8C", studentNumber: 12, studentName: "IBRAHIM ALFARABI" },
  { id: "8c-13", className: "8C", studentNumber: 13, studentName: "KANIA DWI FEBRIANA EFENDY" },
  { id: "8c-14", className: "8C", studentNumber: 14, studentName: "MUCHAMMAD NIZAM RAMADHANI" },
  { id: "8c-15", className: "8C", studentNumber: 15, studentName: "MUHAMAD RIZKY RIAN MAULANA" },
  { id: "8c-16", className: "8C", studentNumber: 16, studentName: "MUHAMMAD HASBI NUR FAIZ" },
  { id: "8c-17", className: "8C", studentNumber: 17, studentName: "MUHAMMAD YUSUF AL GHIFARI" },
  { id: "8c-18", className: "8C", studentNumber: 18, studentName: "MUHAMMAD ZIDANE ZAKYYATHAA FIRMANSYAH" },
  { id: "8c-19", className: "8C", studentNumber: 19, studentName: "NABILA NAYLA RAMADHANI" },
  { id: "8c-20", className: "8C", studentNumber: 20, studentName: "NABILLA DWI SAPUTRI" },
  { id: "8c-21", className: "8C", studentNumber: 21, studentName: "NADHITA INTAN ZAHIRA" },
  { id: "8c-22", className: "8C", studentNumber: 22, studentName: "NAIRA KHANZA AZAHRA" },
  { id: "8c-23", className: "8C", studentNumber: 23, studentName: "NAUFAL ARYA FERDIANSYAH" },
  { id: "8c-24", className: "8C", studentNumber: 24, studentName: "NIZAR INDRASTA AKNA FIRMANSYAH" },
  { id: "8c-25", className: "8C", studentNumber: 25, studentName: "PUTRI SALSA MARCHELLA" },
  { id: "8c-26", className: "8C", studentNumber: 26, studentName: "RAISHA KYNA SEFA AL ANANTA" },
  { id: "8c-27", className: "8C", studentNumber: 27, studentName: "RAJA RIZKY IRAWAN" },
  { id: "8c-28", className: "8C", studentNumber: 28, studentName: "RAKKA ATHALLAH DWISA PRANATA" },
  { id: "8c-29", className: "8C", studentNumber: 29, studentName: "RATU MAHIRA NURRIDHA" },
  { id: "8c-30", className: "8C", studentNumber: 30, studentName: "SALSABILA PUTRI KAMILA" },
  { id: "8c-31", className: "8C", studentNumber: 31, studentName: "SEKAR CAHYA WAHYUNINGRUM" },
  { id: "8c-32", className: "8C", studentNumber: 32, studentName: "SHAQUEL DHAWIY ZHIAN" },

  // ==========================================
  // KELAS 8E (32 Siswa)
  // ==========================================
  { id: "8e-1", className: "8E", studentNumber: 1, studentName: "ADINDA KIRANA FAUZIAH" },
  { id: "8e-2", className: "8E", studentNumber: 2, studentName: "AIREESE ATHALLA FITRA SETIAWAN" },
  { id: "8e-3", className: "8E", studentNumber: 3, studentName: "ALFAHREZI RAYVAN HUDIANSYAH" },
  { id: "8e-4", className: "8E", studentNumber: 4, studentName: "AMELIA DWI ANGGRAENI" },
  { id: "8e-5", className: "8E", studentNumber: 5, studentName: "APRILLIA AZZAHRA" },
  { id: "8e-6", className: "8E", studentNumber: 6, studentName: "AZKA ABDILLAH ALVARO" },
  { id: "8e-7", className: "8E", studentNumber: 7, studentName: "CALISTA ATHAYA ALODIA RAISSA" },
  { id: "8e-8", className: "8E", studentNumber: 8, studentName: "DAFFA ARSYAH FRAMADITYA" },
  { id: "8e-9", className: "8E", studentNumber: 9, studentName: "DEHAN BRAMA ALVARO" },
  { id: "8e-10", className: "8E", studentNumber: 10, studentName: "DUTHA SATRIA A LUMBU" },
  { id: "8e-11", className: "8E", studentNumber: 11, studentName: "FALLEN RAYYAN RAHARDIANSYAH" },
  { id: "8e-12", className: "8E", studentNumber: 12, studentName: "GENDIS KOMALA NUGROHO" },
  { id: "8e-13", className: "8E", studentNumber: 13, studentName: "HAFIZHAN WIDYANATHA" },
  { id: "8e-14", className: "8E", studentNumber: 14, studentName: "KALILA ARIYANTI" },
  { id: "8e-15", className: "8E", studentNumber: 15, studentName: "KANAYA AZALEA NAFISAH" },
  { id: "8e-16", className: "8E", studentNumber: 16, studentName: "KEVIN ALFAHRIZIO WIRASTA" },
  { id: "8e-17", className: "8E", studentNumber: 17, studentName: "KHODIJAH" },
  { id: "8e-18", className: "8E", studentNumber: 18, studentName: "MAHARDIKA AZKA PRADANA" },
  { id: "8e-19", className: "8E", studentNumber: 19, studentName: "MOCHAMAD DICKA APRIANSYAH" },
  { id: "8e-20", className: "8E", studentNumber: 20, studentName: "NOVANDA PUTRA HARDIYANTO" },
  { id: "8e-21", className: "8E", studentNumber: 21, studentName: "NUR AHMAD HABIBUL MAJID" },
  { id: "8e-22", className: "8E", studentNumber: 22, studentName: "PARISYA KANAKA ASADYA" },
  { id: "8e-23", className: "8E", studentNumber: 23, studentName: "PHI THETA CAHYONO PUTRA" },
  { id: "8e-24", className: "8E", studentNumber: 24, studentName: "RAGILDA RACHMA TRI WIJAYANTI" },
  { id: "8e-25", className: "8E", studentNumber: 25, studentName: "RARAS CITRA RAMADHANI" },
  { id: "8e-26", className: "8E", studentNumber: 26, studentName: "RONALDO KURNIA ABHIRAMA" },
  { id: "8e-27", className: "8E", studentNumber: 27, studentName: "RUCITA SASIKIRANA PARAHITA" },
  { id: "8e-28", className: "8E", studentNumber: 28, studentName: "SALWA NISRINA AFIFAH" },
  { id: "8e-29", className: "8E", studentNumber: 29, studentName: "SAQILA FITRI FATIMAH" },
  { id: "8e-30", className: "8E", studentNumber: 30, studentName: "SIFA CHOIRUN NISA" },
  { id: "8e-31", className: "8E", studentNumber: 31, studentName: "TAJUNNISA FARIDATUL ILMI" },
  { id: "8e-32", className: "8E", studentNumber: 32, studentName: "ZAINILA LAILATUL ZAHIRIA" },

  // ==========================================
  // KELAS 9C (32 Siswa)
  // ==========================================
  { id: "9c-1", className: "9C", studentNumber: 1, studentName: "AHMAD ADI DANUARTA" },
  { id: "9c-2", className: "9C", studentNumber: 2, studentName: "ALFAHREZA RAFFASYA CHASAVANI" },
  { id: "9c-3", className: "9C", studentNumber: 3, studentName: "ALMIRA PRAMUSITA PUTRI SETIAWAN" },
  { id: "9c-4", className: "9C", studentNumber: 4, studentName: "AMMAR ARYA PASCA MADA" },
  { id: "9c-5", className: "9C", studentNumber: 5, studentName: "AQILAH IRDINA ZAFARANA" },
  { id: "9c-6", className: "9C", studentNumber: 6, studentName: "ARJUNA ABISHEVA SUSETIADI" },
  { id: "9c-7", className: "9C", studentNumber: 7, studentName: "AUFA ABIYYU BRAMANTY" },
  { id: "9c-8", className: "9C", studentNumber: 8, studentName: "BHADISTA NOOR THALIA" },
  { id: "9c-9", className: "9C", studentNumber: 9, studentName: "CITRA MARCHELLA LATHIFA" },
  { id: "9c-10", className: "9C", studentNumber: 10, studentName: "DHANIYAH AQILAH PUTRI PRASETYO" },
  { id: "9c-11", className: "9C", studentNumber: 11, studentName: "DIANDRA KIRANA MAHESWARI" },
  { id: "9c-12", className: "9C", studentNumber: 12, studentName: "DZAKIRA TALITA AZ ZAHRA" },
  { id: "9c-13", className: "9C", studentNumber: 13, studentName: "GLADYS ELYSIA FAYOLA" },
  { id: "9c-14", className: "9C", studentNumber: 14, studentName: "GLADYS LETICIA ANABELLE DESTINY" },
  { id: "9c-15", className: "9C", studentNumber: 15, studentName: "HAFIZA HANUN SALSABILA RAHMA" },
  { id: "9c-16", className: "9C", studentNumber: 16, studentName: "MARVELLE PUTRA ARDIANSYAH" },
  { id: "9c-17", className: "9C", studentNumber: 17, studentName: "MOCH. ARRA SASTRA INDRA PRATAMA" },
  { id: "9c-18", className: "9C", studentNumber: 18, studentName: "MUHAMAD RIZKI ALIFIAN" },
  { id: "9c-19", className: "9C", studentNumber: 19, studentName: "MUHAMAD ZIDAN PUTRA PRASETYO" },
  { id: "9c-20", className: "9C", studentNumber: 20, studentName: "MUHAMMAD AKBAR NOFA WIJAYA" },
  { id: "9c-21", className: "9C", studentNumber: 21, studentName: "MUHAMMAD BAHRUL HIKMI" },
  { id: "9c-22", className: "9C", studentNumber: 22, studentName: "MUHAMMAD OKTARYAN NUGRAHA" },
  { id: "9c-23", className: "9C", studentNumber: 23, studentName: "MUHAMMAD WILDAN ARYASATYA" },
  { id: "9c-24", className: "9C", studentNumber: 24, studentName: "NAURA SIMA" },
  { id: "9c-25", className: "9C", studentNumber: 25, studentName: "NEVA O-SHINE FITRIA PURI" },
  { id: "9c-26", className: "9C", studentNumber: 26, studentName: "OKTAVIA PERMATA ASARI" },
  { id: "9c-27", className: "9C", studentNumber: 27, studentName: "QUEENSA BERLIANA IASA" },
  { id: "9c-28", className: "9C", studentNumber: 28, studentName: "RADITYA ZIKRI ALKHALIFI" },
  { id: "9c-29", className: "9C", studentNumber: 29, studentName: "RAYHAN SANDI PRATAMA" },
  { id: "9c-30", className: "9C", studentNumber: 30, studentName: "SURYANITA DWI ANGGRAINI" },
  { id: "9c-31", className: "9C", studentNumber: 31, studentName: "YUSUF AR RIDHO" },
  { id: "9c-32", className: "9C", studentNumber: 32, studentName: "ZASKEYA WILDANIA EFFENDY" },

  // ==========================================
  // KELAS 9E (32 Siswa)
  // ==========================================
  { id: "9e-1", className: "9E", studentNumber: 1, studentName: "ACHMAD BIMA KURNIAWAN" },
  { id: "9e-2", className: "9E", studentNumber: 2, studentName: "AHMAD AMRAN RASYIDAN ALI" },
  { id: "9e-3", className: "9E", studentNumber: 3, studentName: "ALDIS PUTRI FIJAYANTI" },
  { id: "9e-4", className: "9E", studentNumber: 4, studentName: "ANASTASIA NADA PARAMITHA WIJAYA" },
  { id: "9e-5", className: "9E", studentNumber: 5, studentName: "ARDELIA ZAFARANI INARAISSA" },
  { id: "9e-6", className: "9E", studentNumber: 6, studentName: "ARMANDO GAVIN DIAN SASMITHA" },
  { id: "9e-7", className: "9E", studentNumber: 7, studentName: "ATHASYAH RANIDIA CALISTA" },
  { id: "9e-8", className: "9E", studentNumber: 8, studentName: "AXELLE ABRAR BHAGAWANTA IBAD" },
  { id: "9e-9", className: "9E", studentNumber: 9, studentName: "AZKA SYADDAD MUSYAFFA EFFENDI" },
  { id: "9e-10", className: "9E", studentNumber: 10, studentName: "BAHA'UDIN ARIEF DHARMAWAN" },
  { id: "9e-11", className: "9E", studentNumber: 11, studentName: "BARA RESTU SAPUTRA" },
  { id: "9e-12", className: "9E", studentNumber: 12, studentName: "CAVALIERO IBRAHIM PATTISAHUSIWA" },
  { id: "9e-13", className: "9E", studentNumber: 13, studentName: "DEVIANA JIHAN KHAIRUNNISA" },
  { id: "9e-14", className: "9E", studentNumber: 14, studentName: "GENTZA RAYHAN ESTU AZZAHIDI" },
  { id: "9e-15", className: "9E", studentNumber: 15, studentName: "HANANIA ATAYA RAMADHANI" },
  { id: "9e-16", className: "9E", studentNumber: 16, studentName: "HASNA LUBNA ATHAYA" },
  { id: "9e-17", className: "9E", studentNumber: 17, studentName: "ICHIGO MIFAZI NUR AISYAH" },
  { id: "9e-18", className: "9E", studentNumber: 18, studentName: "ISNANIYAH AHLIS SHOFA" },
  { id: "9e-19", className: "9E", studentNumber: 19, studentName: "M.GALE PRAKOSO" },
  { id: "9e-20", className: "9E", studentNumber: 20, studentName: "MOCHAMAD KEVIN PUTRA WIBOWO" },
  { id: "9e-21", className: "9E", studentNumber: 21, studentName: "MUHAMMAD EVAN SETIAWAN" },
  { id: "9e-22", className: "9E", studentNumber: 22, studentName: "MUHAMMAD RADITHYA JAVAS AKBAR" },
  { id: "9e-23", className: "9E", studentNumber: 23, studentName: "MUHAMMAD YARDAN WIRYAMANTA" },
  { id: "9e-24", className: "9E", studentNumber: 24, studentName: "NAJWA HAFI AZZAHRA" },
  { id: "9e-25", className: "9E", studentNumber: 25, studentName: "NAZZA AULIA RAHMA" },
  { id: "9e-26", className: "9E", studentNumber: 26, studentName: "NEYSHA ALZENA SAFIRA" },
  { id: "9e-27", className: "9E", studentNumber: 27, studentName: "ORLIN ONDINE HENDRA KUMARA" },
  { id: "9e-28", className: "9E", studentNumber: 28, studentName: "RAFI BAGUS PRABOWO" },
  { id: "9e-29", className: "9E", studentNumber: 29, studentName: "RISKY SATRIYO PAMUNGKAS" },
  { id: "9e-30", className: "9E", studentNumber: 30, studentName: "SUKMA AYU PRAMESWARI" },
  { id: "9e-31", className: "9E", studentNumber: 31, studentName: "WINIA CANTIKA LAUREN" },
  { id: "9e-32", className: "9E", studentNumber: 32, studentName: "ZAHRAH SYIFA NAFEEZA YULIANTI" },

  // ==========================================
  // KELAS 9F (32 Siswa)
  // ==========================================
  { id: "9f-1", className: "9F", studentNumber: 1, studentName: "AIZA SYABILLA MUMTAZZA" },
  { id: "9f-2", className: "9F", studentNumber: 2, studentName: "ALEESYA DANIA HIDAYAT" },
  { id: "9f-3", className: "9F", studentNumber: 3, studentName: "ALESIA SIERRA NURANI" },
  { id: "9f-4", className: "9F", studentNumber: 4, studentName: "ALEXA MECKENZIE TYANDRA" },
  { id: "9f-5", className: "9F", studentNumber: 5, studentName: "ALFIANSYACH ANANG SAPUTRA" },
  { id: "9f-6", className: "9F", studentNumber: 6, studentName: "ANDRA RAMANIA RADISTA" },
  { id: "9f-7", className: "9F", studentNumber: 7, studentName: "ARYA OKTAVIAN PUTRA" },
  { id: "9f-8", className: "9F", studentNumber: 8, studentName: "ASKA AL FARUQ" },
  { id: "9f-9", className: "9F", studentNumber: 9, studentName: "ASYRAF MUSYAFFA ALKAF" },
  { id: "9f-10", className: "9F", studentNumber: 10, studentName: "AVRIZAL RIZKY RHOMADHON" },
  { id: "9f-11", className: "9F", studentNumber: 11, studentName: "BARA KIESHA ALVARO" },
  { id: "9f-12", className: "9F", studentNumber: 12, studentName: "BILQIIS NABILA INTAN KAROMAH" },
  { id: "9f-13", className: "9F", studentNumber: 13, studentName: "DAHLIA FITRIANINGRUM" },
  { id: "9f-14", className: "9F", studentNumber: 14, studentName: "DEVITA MAHARANI" },
  { id: "9f-15", className: "9F", studentNumber: 15, studentName: "DIANDRA ADELINA" },
  { id: "9f-16", className: "9F", studentNumber: 16, studentName: "FREZA ATHAYA ALFARIZKY" },
  { id: "9f-17", className: "9F", studentNumber: 17, studentName: "KENYA JELITA PRAMONO" },
  { id: "9f-18", className: "9F", studentNumber: 18, studentName: "LEBANOUIST OCTHA PARA YUDHA PUTRA" },
  { id: "9f-19", className: "9F", studentNumber: 19, studentName: "MOCHAMMAD ARYA ZAKKI PRASETYA" },
  { id: "9f-20", className: "9F", studentNumber: 20, studentName: "MUHAMMAD DHARMAWANGSA" },
  { id: "9f-21", className: "9F", studentNumber: 21, studentName: "MUHAMMAD HAIKAL ABDILLAH" },
  { id: "9f-22", className: "9F", studentNumber: 22, studentName: "NADHIF ARIEF ASHIDDIQ" },
  { id: "9f-23", className: "9F", studentNumber: 23, studentName: "NAOZSI ELLENA DIANDRA AQILLA" },
  { id: "9f-24", className: "9F", studentNumber: 24, studentName: "NOVITA ANGGRAENY" },
  { id: "9f-25", className: "9F", studentNumber: 25, studentName: "RAISSA AQILA" },
  { id: "9f-26", className: "9F", studentNumber: 26, studentName: "SABRINA YURI PARAMITA" },
  { id: "9f-27", className: "9F", studentNumber: 27, studentName: "SATRIA NUGRAHA SUYOKO PUTRA" },
  { id: "9f-28", className: "9F", studentNumber: 28, studentName: "SHAFIRA DEVITA PRILYLA" },
  { id: "9f-29", className: "9F", studentNumber: 29, studentName: "SHAVIERA AULIA ANDHIKA" },
  { id: "9f-30", className: "9F", studentNumber: 30, studentName: "YULIAUSY CITRASARI" },
  { id: "9f-31", className: "9F", studentNumber: 31, studentName: "ZAHIRAH KARIMATUN NISSAK" },
  { id: "9f-32", className: "9F", studentNumber: 32, studentName: "MEGA AULIA" },
];

export function getStudentsByClass(className: string): Student[] {
  return MASTER_ROSTER.filter((item) => item.className === className);
}

export function validateStudent(className: string, absen: number): Student | undefined {
  return MASTER_ROSTER.find(
    (item) => item.className === className && item.studentNumber === absen
  );
}
